# Generated by Django 6.0 on 2026-09-01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('power', models.PositiveIntegerField()),
                ('displacement', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fuel', models.CharField(max_length=50)),
                ('gear', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ('brand', 'model', 'year'),
            },
        ),
    ]
