# Generated by Django 6.1 on 2026-09-02 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Вид топлива')),
            ],
            options={
                'verbose_name': 'Вид топлива',
                'verbose_name_plural': 'Виды топлива',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Коробка передач')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('brand', 'model', 'year', 'mileage'), 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='car',
            name='displacement',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.PositiveIntegerField(verbose_name='Мощность, л.с.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.fuel', verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.gear', verbose_name='Коробка передач'),
        ),
    ]
