# Generated by Django 6.1 on 2026-09-03 12:16

import django.db.models.deletion
import utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_color_fuel_gear_alter_car_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус автомобиля',
                'verbose_name_plural': 'Статусы автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.gear', verbose_name='Трансмиссия'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(default=None, null=True, upload_to=utils.get_image_upload_path, verbose_name='Изображение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Изображение автомобиля',
                'verbose_name_plural': 'Изображения автомобилей',
                'ordering': ['car'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.carstatus', verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
