# Generated by Django 6.1 on 2026-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carstatus_alter_car_gear_carimage_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=20, verbose_name='VIN-номер'),
        ),
        migrations.AddField(
            model_name='carimage',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
