# Generated by Django 6.1 on 2026-09-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_vin_carimage_visible_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
