# Generated by Django 6.1 on 2026-09-04 10:11

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carimage_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=utils.get_image_upload_path, verbose_name='Изображение'),
        ),
    ]
