# Generated by Django 6.1 on 2026-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='visible',
        ),
        migrations.AddField(
            model_name='carimage',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Публичное'),
        ),
    ]
