# Generated by Django 6.1 on 2026-09-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_carimage_visible_carimage_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
