# Generated by Django 6.1 on 2026-09-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carimage_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'ordering': ['car', 'index'], 'verbose_name': 'Изображение автомобиля', 'verbose_name_plural': 'Изображения автомобилей'},
        ),
    ]
